/**
 *  Copyright 2007 by Benjamin J. Land (a.k.a. BenLand100)
 *
 *  This file is part of the CBAS C-Based Autoing System
 *
 *  CBAS is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  CBAS is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with CBAS. If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cbas_CodeEditor */

#ifndef _Included_cbas_CodeEditor
#define _Included_cbas_CodeEditor
#ifdef __cplusplus
extern "C" {
#endif
#undef cbas_CodeEditor_FOCUS_TRAVERSABLE_UNKNOWN
#define cbas_CodeEditor_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef cbas_CodeEditor_FOCUS_TRAVERSABLE_DEFAULT
#define cbas_CodeEditor_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef cbas_CodeEditor_FOCUS_TRAVERSABLE_SET
#define cbas_CodeEditor_FOCUS_TRAVERSABLE_SET 2L
#undef cbas_CodeEditor_TOP_ALIGNMENT
#define cbas_CodeEditor_TOP_ALIGNMENT 0.0f
#undef cbas_CodeEditor_CENTER_ALIGNMENT
#define cbas_CodeEditor_CENTER_ALIGNMENT 0.5f
#undef cbas_CodeEditor_BOTTOM_ALIGNMENT
#define cbas_CodeEditor_BOTTOM_ALIGNMENT 1.0f
#undef cbas_CodeEditor_LEFT_ALIGNMENT
#define cbas_CodeEditor_LEFT_ALIGNMENT 0.0f
#undef cbas_CodeEditor_RIGHT_ALIGNMENT
#define cbas_CodeEditor_RIGHT_ALIGNMENT 1.0f
#undef cbas_CodeEditor_serialVersionUID
#define cbas_CodeEditor_serialVersionUID -7644114512714619750LL
#undef cbas_CodeEditor_serialVersionUID
#define cbas_CodeEditor_serialVersionUID 4613797578919906343LL
#undef cbas_CodeEditor_INCLUDE_SELF
#define cbas_CodeEditor_INCLUDE_SELF 1L
#undef cbas_CodeEditor_SEARCH_HEAVYWEIGHTS
#define cbas_CodeEditor_SEARCH_HEAVYWEIGHTS 1L
#undef cbas_CodeEditor_OPENED
#define cbas_CodeEditor_OPENED 1L
#undef cbas_CodeEditor_serialVersionUID
#define cbas_CodeEditor_serialVersionUID 4497834738069338734LL
#undef cbas_CodeEditor_DEFAULT_CURSOR
#define cbas_CodeEditor_DEFAULT_CURSOR 0L
#undef cbas_CodeEditor_CROSSHAIR_CURSOR
#define cbas_CodeEditor_CROSSHAIR_CURSOR 1L
#undef cbas_CodeEditor_TEXT_CURSOR
#define cbas_CodeEditor_TEXT_CURSOR 2L
#undef cbas_CodeEditor_WAIT_CURSOR
#define cbas_CodeEditor_WAIT_CURSOR 3L
#undef cbas_CodeEditor_SW_RESIZE_CURSOR
#define cbas_CodeEditor_SW_RESIZE_CURSOR 4L
#undef cbas_CodeEditor_SE_RESIZE_CURSOR
#define cbas_CodeEditor_SE_RESIZE_CURSOR 5L
#undef cbas_CodeEditor_NW_RESIZE_CURSOR
#define cbas_CodeEditor_NW_RESIZE_CURSOR 6L
#undef cbas_CodeEditor_NE_RESIZE_CURSOR
#define cbas_CodeEditor_NE_RESIZE_CURSOR 7L
#undef cbas_CodeEditor_N_RESIZE_CURSOR
#define cbas_CodeEditor_N_RESIZE_CURSOR 8L
#undef cbas_CodeEditor_S_RESIZE_CURSOR
#define cbas_CodeEditor_S_RESIZE_CURSOR 9L
#undef cbas_CodeEditor_W_RESIZE_CURSOR
#define cbas_CodeEditor_W_RESIZE_CURSOR 10L
#undef cbas_CodeEditor_E_RESIZE_CURSOR
#define cbas_CodeEditor_E_RESIZE_CURSOR 11L
#undef cbas_CodeEditor_HAND_CURSOR
#define cbas_CodeEditor_HAND_CURSOR 12L
#undef cbas_CodeEditor_MOVE_CURSOR
#define cbas_CodeEditor_MOVE_CURSOR 13L
#undef cbas_CodeEditor_NORMAL
#define cbas_CodeEditor_NORMAL 0L
#undef cbas_CodeEditor_ICONIFIED
#define cbas_CodeEditor_ICONIFIED 1L
#undef cbas_CodeEditor_MAXIMIZED_HORIZ
#define cbas_CodeEditor_MAXIMIZED_HORIZ 2L
#undef cbas_CodeEditor_MAXIMIZED_VERT
#define cbas_CodeEditor_MAXIMIZED_VERT 4L
#undef cbas_CodeEditor_MAXIMIZED_BOTH
#define cbas_CodeEditor_MAXIMIZED_BOTH 6L
#undef cbas_CodeEditor_serialVersionUID
#define cbas_CodeEditor_serialVersionUID 2673458971256075116LL
#undef cbas_CodeEditor_EXIT_ON_CLOSE
#define cbas_CodeEditor_EXIT_ON_CLOSE 3L
/*
 * Class:     cbas_CodeEditor
 * Method:    implNativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbas_CodeEditor_implNativeInit
  (JNIEnv *, jobject);

/*
 * Class:     cbas_CodeEditor
 * Method:    implPause
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cbas_CodeEditor_implPause
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cbas_CodeEditor
 * Method:    implStop
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cbas_CodeEditor_implStop
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cbas_CodeEditor
 * Method:    implRun
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cbas_CodeEditor_implRun
  (JNIEnv *, jobject, jstring);


/*
 * Class:     cbas_CodeEditor
 * Method:    implExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cbas_CodeEditor_implExit
  (JNIEnv *, jobject);


/*
 * Class:     cbas_CodeEditor
 * Method:    implReleaseLib
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cbas_CodeEditor_implReleaseLib
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
